version: '3.4'

services:
  tanakinator2-api:
    image: tanakinator2-api
    build:
      context: .
      dockerfile: ./Dockerfile

  tanakinator2-db:
    image: mysql:8.0-debian
    ports:
      - "13306:3306"
    env_file:
      - mysql.env
    # volumes:
    #   - ./volumes/mysql:/var/lib/mysql
